### ISSUE TITLE
Ther seems to be a Problem with Tarma Root

### ISSUE THREAD

**Issue by TsXTatzumi** [MinecraftschurliMods/Ars-Magica-Legacy#242]
repeatedly encountered around: 

x=-509, y=108, z=-415
seed: -9208904052884796592
worldtype: default

forge: 39.0.18
mods:
arsmagicalegacy-1.18.1-0.0.4
Patchouli-1.18.1-64

[crash-2022-01-11_19.49.50-server.txt](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/7849197/crash-2022-01-11_19.49.50-server.txt)

**Comment by Baggytrousers27** [comment]
Having a similar issue in swamps. Game freezes, have to end task and recieve this error

_The game crashed whilst exception ticking world
Error: java.lang.NoSuchFieldError: DIRT
Exit Code: 1_

1.18.1 Forge 39.0.18
arsmagicalegacy-1.18.1-0.0.4
Patchouli-1.18.1-63
jei-1.18.1-9.1.2.61

[Crashlog](https://pastebin.com/Ndg6vfKk)

**Comment by Minecraftschurli** [comment]
this is an issue with forge 39.0.18
in that version they removed the DIRT field in the error log
for now downgrade the forge version to 39.0.17
