### ISSUE TITLE
Beam

### ISSUE THREAD

**Issue by esFaultier** [MinecraftschurliMods/Ars-Magica-Legacy#244]
Hi ich habe mir gestern die mod heruntergeladen und habe gesehen das Zauber mit beam nicht funktionieren.

**Comment by IchHabeHunger54** [comment]
Beam doesn't work yet, therefore it is flagged marked as WIP (work in progress). See issue #16.

**Comment by IchHabeHunger54** [comment]
Oh wait, I just realised it isn't even flagged... gonna change that right now.
