### ISSUE TITLE
Failure to load on forge 39.0.66

### ISSUE THREAD

**Issue by Baggytrousers27** [MinecraftschurliMods/Ars-Magica-Legacy#256]
Ars Magica: Legacy (arsmagicalegacy) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

arsmagicalegacy-1.18.1-0.1.0
Patchouli-1.18.1-65
jei-1.18.1-9.2.3.84

[Crashlog (With JEI)](https://pastebin.com/kGxKnkU1)
[Crashlog (Without JEI)](https://pastebin.com/hvLS07ny)

**Comment by Minecraftschurli** [comment]
This is an issue with the newest forge version, we will publish a fixed version ASAP. 
Use the previous version of forge for now.

Announcement from forge:
~~~
PSA tools 

I've just merged the PR which fixes the FoliagePlacerType and TreeDecoratorType registries i missed in porting.
Modders can now use DeferredRegister to access these types, and any reference to Registry.register outside of the Registry events will cause a crash.

If you're encountering crashes from this (the version is 39.0.66 (NOT .21)), then you must wait for the affected mod to fix the problem.
This is a breaking change late into the cycle, which i hate doing, but it's necessary and rather minor.
Sorry for the inconvenience here.
~~~
