### ISSUE TITLE
[Bug]: Opening occulus in multiplayer crashes the client

### ISSUE THREAD

**Issue by AeroFW** [MinecraftschurliMods/Ars-Magica-Legacy#271]
### Describe the bug

Opening occulus crashes the game instantly.

Version 1.18.2-1.0.0
forge 40.0.36

The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
Exit Code: -1

Unsure of how to replicate issue. Friend and I were both playing and we couldn't use it at all. It suddenly started working for him at some point. Then stopped. And started working for me. Both of us can use it again now. Not sure why it was acting strange.

As soon as it stopped working on the multiplayer server him and I went to single player worlds and put one down. The occulus worked there. It was maybe 10 minutes after that the occulus worked for him on multiplayer. Another 10 minutes and then it started working for me too totaling about 20 minutes of wait for me. During the wait we broke it and placed it back down numerous times. Crashed numerous times as well.

It should maybe be noted that the inscription table right next to it stopped working suddenly too. No crashing just right clicking did nothing. However breaking it and placing it back down seemed to fix it instantly.

### Version

1.18.1-1.0.0

### Forge Version

40.0.36

### Other Mods

[Awesome Dungeon The End edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-the-end-forge)
[Ars Magica: Legacy (by Minecraftschurli)](https://www.curseforge.com/minecraft/mc-mods/ars-magica-legacy)
[Meet Your Fight (by Lykrast)](https://www.curseforge.com/minecraft/mc-mods/meet-your-fight)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Tough As Nails (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Collective (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Epic Knights: Shields, Armor and Weapons (by magistu_)](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons)
[MCDoom (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/mcdoom)
[Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Sons Of Sins (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/sons-of-sins)
[Healing Campfire (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
[Vampirism - Become a vampire! (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)

**Comment by BlackShadow77** [comment]
Ehy, i found same problem running a minecraft server on 1.18.1 can u fix it also for 1.18.1?
