### ISSUE TITLE
[Bug]: Items for Spell Casting dont appear above lectern

### ISSUE THREAD

**Issue by REDPANDAS2105** [MinecraftschurliMods/Ars-Magica-Legacy#273]
### Describe the bug

@ @So when i make a spell and put it in the lectern nothing happens. but if i throw a blank rune into the space i hear a ding noise and it disapears. Ive tried differetn versions, and different alters. On youtube the only videos are in rusion but also didnt help. So i thought id let you guys know. But thanks for porting this.

### Steps to Reproduce

every time i open 

### Expected behavior

The ingredients appeard

### Version

1.18.1-0.1.5

### Forge Version

39.1.0

**Comment by IchHabeHunger54** [comment]
Update, this issue has been fixed in 1.0.0.
