### ISSUE TITLE
[Bug]: Not Compatiable with Newest versions of JEI

### ISSUE THREAD

**Issue by Daihok41** [MinecraftschurliMods/Ars-Magica-Legacy#274]
### Describe the bug

Version 1.18.2 1.0.1 of Ars magic Not compatiable with newest 1.18.2 versions of JEI. Causes crash with no crash reports.

### Version

1.18.2-1.0.1

### Forge Version

40.0.45

### Other Mods

Jei 1.18.2 10.0.0.191

**Comment by Minecraftschurli** [comment]
We currently only support jei between 9.1 and 10 (we didn't test with 10 yet)
