### ISSUE TITLE
[Bug]: Dig spells will often fail to cast

### ISSUE THREAD

**Issue by Gronglegrowth** [MinecraftschurliMods/Ars-Magica-Legacy#275]
### Describe the bug

I have only tested this with two spells; a Touch > Dig and a Projectile > Dig. The former worked after crafting it, until I entered the customization gui and renamed it, then it failed to cast itself every time. The latter did not work at all.

### Steps to Reproduce

1. Create one of the spells mentioned above (possibly others, have not yet tested)
2. Attempt to cast it; it will likely not work.

### Expected behavior

The spells should break the blocks I target with no issue

### Version

1.18.2-1.0.1

### Forge Version

40.0.40

### Other Mods

- Patchouli 1.18.2-67
- Backpacked 2.1.5-1.18.2
- Catalogue 1.6.1-1.18.2
- Configured 1.5.3-1.18.2
- Curios API 1.18.2-5.0.6.3
- Ferrite Core 4.2.0
- JEI 1.18.2-9.5.5.174
- Paucal 1.18.2-0.3.2
- Potion Bundles 1.18.1-1.3
- Rubidium 0.5.2a
- Simple Maps 0.3.1
- The One Probe 1.18-5.1.0
- Voodoo 1.18.1-1.0.2

### Log

```shell
The paste of the log here exceeded character limit, see https://pastebin.com/i9BzsQQz
```

**Comment by IchHabeHunger54** [comment]
A few questions for context.

1) Are you in creative or survival? Did you switch, if so, when?

2) Did you learn magic (that is, craft the compendium) beforehand?

3) Am I getting this right: You were giving the Touch-Dig spell an icon and a name. Spell casting worked after that. Then, you renamed it, and from that point it didn't work?

**Comment by Gronglegrowth** [comment]
I started the world in creative, switched to survival shortly after I loaded it, then switched back to creative to test spell crafting. I don't remember if I crafted the compendium or if I had given it to myself, but am thinking it was the latter. And yes, for the Touch > Dig spell it worked after initially naming and iconing it, but renaming it again caused it to not work.

**Comment by IchHabeHunger54** [comment]
I can't reproduce this bug, testing with Projectile-Dig.
I can normally cast it in both creative and survival, even after renaming.
Please provide a more specific description (for example a video, showing that it doesn't work, alongside all steps taken).
