### ISSUE TITLE
[Bug] Server crashing on impact of projectile-zone-regen spell

### ISSUE THREAD

**Issue by Cazy-Kun** [MinecraftschurliMods/Ars-Magica-Legacy#289]
When doing the following spell and casting the spell as soon as the spell touch a block it crashes the server. I'll leave the debug.log of the server event in the attachments. 

<Projectile + Zone --> Regeneration>
[debug.log](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8692552/debug.log)

**Comment by IchHabeHunger54** [comment]
This bug is unreproducable for me in a dev environment, both in singleplayer and multiplayer. Could you try reproducing only with AM: Legacy and Patchouli?
