### ISSUE TITLE
[Bug]: Server Closed

### ISSUE THREAD

**Issue by Tyrius1** [MinecraftschurliMods/Ars-Magica-Legacy#303]
### Describe the bug

Was alt tabbed editing configs and when I alt tabbed back it was closed

### Version

1.18.2-1.1.0

### Forge Version

40.1.31

### Log

```shell
https://pastebin.com/39LAZPzz
```

**Comment by Minecraftschurli** [comment]
The cause is that a dryad made something from the mod `biomemakeover` grow and that crashed the game. Please report the issue to them.
