### ISSUE TITLE
[Bug]: Client crashes upon jumping on dedicated server

### ISSUE THREAD

**Issue by aking4125** [MinecraftschurliMods/Ars-Magica-Legacy#304]
### Describe the bug

Hello,

Upon jumping on a dedicated server. The client crashes with the following [crash report](https://crashy.net/cgYNaSP8p1lU4bGZdBbt):  
[crash-2022-06-03_13.52.20-client.txt](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8834639/crash-2022-06-03_13.52.20-client.txt)

Client Log: [debug.zip](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8834763/debug.zip) (Over 25MB, Slightly newer than below as I was doing a Single Player Test)
Server Log (Though there isn't any useful information: [debug.zip](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8834769/debug.zip) (Over 25MB)

I thought it was some type of key conflict but it's not. Removing Ars Magica Legacy fixes this issue. This issue only occurs on a dedicated server. Single Player works fine.

Any ideas?

### Steps to Reproduce

1. Enter a dedicated server
2. Press Space bar (Or your Jump key)
3. Crash / Disconnect

### Expected behavior

Not crash upon jumping?

### Version

1.18.2-1.1.0

### Forge Version

40.1.31

### Other Mods

I hit github maximum 65536 characters limit.

### Log

```shell
Log uploaded above. Github won't load if it's posted here. Sorry.
```

**Comment by twothe** [comment]
I had a similar issue when I was falling into a visualized Crafting Altar:
[crash-2022-06-26_19.02.30-client.txt](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8987089/crash-2022-06-26_19.02.30-client.txt)
