### ISSUE TITLE
[Bug]: Boss Health Bar of Water Guardian not disappearing

### ISSUE THREAD

**Issue by Shorepion** [MinecraftschurliMods/Ars-Magica-Legacy#309]
### Describe the bug

-The boss' health bar/s of a defeated water guardian (and of his clones) not disappearing
-In Singleplayer and Multiplayer
-Rejoining fixes this

### Steps to Reproduce

-Summon water guradian
-Defeating boss
-Result: Boss Health Bar/s still remain

### Expected behavior

-Expecting the boss bar/s to vanish after the boss' death

### Screenshots

video example: https://www.youtube.com/watch?v=hMIQvJjDQyk

### Version

1.18.2-1.1.0

### Forge Version

40.1.48

### Other Mods

![modlist](https://user-images.githubusercontent.com/24994890/174457245-7251850e-d407-4864-a580-05f95a27d66a.JPG)

Additional mod 'Progressive Bosses', which appears to have the impact on this bug.

### Log

```shell
-
```

**Comment by Shorepion** [comment]
https://github.com/Insane96/ProgressiveBosses/issues

**Comment by Minecraftschurli** [comment]
does this still occur on the latest version?

**Comment by IchHabeHunger54** [comment]
Closed due to inactivity.
