### ISSUE TITLE
[Bug]: Using a gravity projectile causes a server crash

### ISSUE THREAD

**Issue by AlchemicalSoul** [MinecraftschurliMods/Ars-Magica-Legacy#319]
### Describe the bug

When I put projectile then gravity and made a spell out of it, casting it caused my minecraft server to crash.

### Steps to Reproduce

1. put projectile gravity in the inscription table.
2. make the spell.
3. use it and crash.

### Expected behavior

To not crash a server.

### Version

1.18.2-1.1.2

### Forge Version

40.1.73

**Comment by AlchemicalSoul** [comment]
Correction, it still crashes, but my guess is because i was crafting it wrong.

**Comment by Minecraftschurli** [comment]
Does this still occur on the latest version?

**Comment by IchHabeHunger54** [comment]
Closed due to inactivity.
