### ISSUE TITLE
[Bug]: Scale Attribute not present on modded entities

### ISSUE THREAD

**Issue by luffykick** [MinecraftschurliMods/Ars-Magica-Legacy#321]
Issue:
I get this crash randomly on arsmagicalegacy-1.18.2-1.1.3.jar seems like it happens on the previous version also.

Forge version: 40.1.71
MC: 1.18.2

Steps to reproduce: 
I am in a heavily modded pack... it also happenes when spawning a bedrock golem from extragolems mod

https://gist.github.com/luffykick/5c2ede8fe876dd25a7cd837670cb93f8

**Comment by Minecraftschurli** [comment]
this is a bug with some entities from other mods but we do not currently know why it happens

**Comment by Minecraftschurli** [comment]
after some investigation it is a problem with how EvilCraft handles the entity attribute registration and not us
