### ISSUE TITLE
[Bug]: Spell books 

### ISSUE THREAD

**Issue by FluffyDogge** [MinecraftschurliMods/Ars-Magica-Legacy#332]
### Describe the bug

so when i craft a spell in my table (for ex: touch/dig) I will grab the book and it will come out already signed and nothing is in the book for crafting a recipe 

### Version

1.18.2-1.1.5

### Forge Version

40.1.76

**Comment by IchHabeHunger54** [comment]
The text is not yet implemented, but the rest already works. Just build the altar and put the book into the lectern. The required items will appear above the lectern.

**Comment by FluffyDogge** [comment]
it doesnt show anything aboce the lecturn either

**Comment by IchHabeHunger54** [comment]
Remove Optifine and/or Rubidium if present. If the issue persists after doing so, please join the Discord so we can nail it down.
