### ISSUE TITLE
help wanted: Too many Dryads in forest biomes.

### ISSUE THREAD

**Issue by Zyphoir** [MinecraftschurliMods/Ars-Magica-Legacy#336]
I was wondering if there was a way to turn down the spawn rate of dryads as they seem to be spawning in groups at a time.
I've tried to lower how much they can bone meal around (radius)/ how much they can bone meal at a time.
I'm playing a custom minecraft modpack that a friend made me in version 1.19.2 and I've lowered minecraft's own spawn rates to see if that would help but it didn't. @Minecraftschurli

**Comment by Minecraftschurli** [comment]
In 1.19 you can turn down the spawn rates with a datapack overriding the biome modifier that adds dryad spawning

**Comment by Zyphoir** [comment]
> In 1.19 you can turn down the spawn rates with a datapack overriding the biome modifier that adds dryad spawning

Is there a specific datapack or its in normal minecraft already?
Sorry, I never use datapacks before.

**Comment by IchHabeHunger54** [comment]
It's part of the mod. Join the Discord, I'm gonna put together the datapack needed and send it into the Ars Magica channel.
