### ISSUE TITLE
[Bug]: Proj + Place Block Crash

### ISSUE THREAD

**Issue by 10BamberJ** [MinecraftschurliMods/Ars-Magica-Legacy#341]
### Describe the bug

Made a Proj + Place Block and Shift + C and Crashed a Server. Here's the crash log
https://bytebin.lucko.me/sVAy28w1Kv

Version of mod arsmagicalegacy-1.19.2-1.2.1.jar

### Steps to Reproduce

1. Crafted a Proje + Place Block
2. Pressed Shift + M
3. Then Crashed

### Expected behavior

Wanted to find the key to copy the block with the spell and place it as that's what the placeblock spell does.
(Shift + Rightclick with spell and it copies the block allowing you to place it.)

### Version

1.19.2-1.2.0

### Forge Version

Forge - 43.1.47

### Other Mods

![Capture](https://user-images.githubusercontent.com/35050624/208202585-5fc8b2c2-da3d-4950-a57f-c2327b41dc59.PNG)

**Comment by Minecraftschurli** [comment]
@IchHabeHunger54 
Additional context:
- Erroring code: `Spell.java:184`
- It looks like the shape group is empty and causes an exception
- Possible solution: add check before `getLast` call and return if empty
