### ISSUE TITLE
[Bug]: 1.19 Touch Spell Shape not Targeting the correct block

### ISSUE THREAD

**Issue by SjetCraft** [MinecraftschurliMods/Ars-Magica-Legacy#344]
### Describe the bug

When using the 'Touch' spell shape, the spell effect 'dig' is not applied to the targeted block.
It seems to be targeting the block originating from the player's 'location' or 'feet'.
Attaching a video

### Screenshots

https://user-images.githubusercontent.com/24903975/208748495-163150df-9757-4b7e-80da-33ed0d52bd65.mp4

### Version

1.19.2-1.2.2

### Forge Version

43.2.1

**Comment by Minecraftschurli** [comment]
Can you reproduce this in the latest version of the mod?

**Comment by SjetCraft** [comment]
My apologies the version is arsmagicalegacy-1.19.2-1.2.2.jar
I have edited the original post.
