### ISSUE TITLE
Mana Creeper Spawning

### ISSUE THREAD

**Issue by ElasticKnife** [MinecraftschurliMods/Ars-Magica-Legacy#345]
Mana creeper seems to be ignoring spawning rules.  This issue could be either a bug/feature request depending on the behavior.  They seem to be spawning consistently in groups of 4, ignoring lighting, ignoring proximity, and ignoring surface type such as spawning in the middle of the ocean, and spawning far too frequently.
Thanks for all the work that you've done reviving this mod!

**Comment by Minecraftschurli** [comment]
To help you we need the mod and forge version you are using

**Comment by ElasticKnife** [comment]
Ah my bad.
Forge: 43.1.52
Mod: 1.2.2

**Comment by IchHabeHunger54** [comment]
Has been resolved in-dev and will be fixed in the next update.

**Comment by ElasticKnife** [comment]
Thanks I appreciate it, keep up the good work!
