### ISSUE TITLE
[Bug]: Inscription table issue

### ISSUE THREAD

**Issue by Nubiluma** [MinecraftschurliMods/Ars-Magica-Legacy#371]
### Describe the bug

The inscription table seems to only update visually when removing any spell components. When I craft the spell recipe or exit and re-enter the GUI, the deleted spell parts are still there and they are also written in the spell recipe. I can quick fix this issue by breaking and placing the table again.

### Steps to Reproduce

1. Enter the inscription table GUI
2. Add spell components and remove some of them
3. Close and re-open the GUI
4. (Maybe repeat this a few times until you get the issue, but it should occur very quickly)

### Expected behavior

- Placed spell components in GUI should remain the same after re-entering the GUI
- Spell recipes should not contain deleted spell components

### Version

1.18.2-1.2.4

### Forge Version

40.2.0

### Other Mods

- patchouli 1.18.2-71.1
- over 100 other mods which I can provide if neccessary
- I do not use Optifine

**Comment by IchHabeHunger54** [comment]
This issue is kind of known, it lies deep within and is the result of the inscription table being kind of an internal mess. We plan on reworking it eventually:tm:, but no guarantees on when.
One question, are you using Rubidium? If so, could you try to reproduce without it?

**Comment by Nubiluma** [comment]
I see, thanks for the fast reply though!
No, I do not use Rubidium.
