### ISSUE TITLE
[Bug]: Black aurem upgrades

### ISSUE THREAD

**Issue by LoneWolf137** [MinecraftschurliMods/Ars-Magica-Legacy#374]
### Describe the bug

The upgrades for the black aurem dont work. Also the compendium entrance does not list the sunstone/moonstone requirements on the rituals of corruption/purification.

### Steps to Reproduce

build black aurem and the upgrades, compare to non upgraded version , see no difference
And the compendium entrances.

### Version

1.18.2-1.2.4

### Forge Version

40.2.1

### Other Mods

-jei-1.18.2-forge-10.2.1.283
-Patchouli-1.18.2-71.1
-geckolib-forge-1.18-3.0.45
-theoneprobe-1.18-5.1.2

**Comment by Minecraftschurli** [comment]
Fixed in dev, included in next release
