### ISSUE TITLE
1.18.2 [Bug]: crash when killed with magic

### ISSUE THREAD

**Issue by border999** [MinecraftschurliMods/Ars-Magica-Legacy#375]
### Describe the bug

crash when killed with magic

### Steps to Reproduce

open a world, spawn something that attacks with magic, get killed by it, crash

### Screenshots

![Screenshot 2023-02-23 124459](https://user-images.githubusercontent.com/11824584/220988577-7af8f070-428d-4213-8ad2-488e4e91b914.jpg)

### Forge Version

1.18.2-40.2.0

### Log

```shell
https://gist.github.com/border999/37faf4aa7bbf3ac93eab10ef1f33f04b
```

**Comment by IchHabeHunger54** [comment]
What specific entity did you use to produce the crash?

**Comment by border999** [comment]
anubis from grimoire of Gaia

**Comment by IchHabeHunger54** [comment]
Alright, it will be looked into.

**Comment by border999** [comment]
but I also know there is a bug(insect) from the same mod that fires magic projectiles and causes the same issue

**Comment by Minecraftschurli** [comment]
The log looks like it is botania that is causing the crash

**Comment by border999** [comment]
vaskii ain't responding

**Comment by border999** [comment]
fixed on Grimoire of Gaia's end.
