### ISSUE TITLE
[Bug]: Spellbooks cannot scroll in offhand unless main hand is empty

### ISSUE THREAD

**Issue by Jackiecrazy** [MinecraftschurliMods/Ars-Magica-Legacy#380]
### Describe the bug

The spellbook sync packet only [checks for an empty main hand](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/blob/cc963bbd46959d749cacf96ca1a396a547b657bc/src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/network/SpellBookNextSpellPacket.java#L35) (and not invalid items) before going to the offhand, so any item in the main hand will block offhand spell swapping.

### Steps to Reproduce

1. Put a spellbook into your offhand, and any other item in your main hand.
2. Shift-scroll.

### Version

1.19.2-1.2.4

### Forge Version

43.2.8

**Comment by Minecraftschurli** [comment]
yes you're right we'll fix it in the next version

**Comment by IchHabeHunger54** [comment]
Fix will ship with the next update.
