### ISSUE TITLE
[Bug]: Mana regeneration rate resetting after death

### ISSUE THREAD

**Issue by ArcaneTreatise** [MinecraftschurliMods/Ars-Magica-Legacy#382]
### Describe the bug

When levelling up, the mana regeneration rate increases with it. However, death seems to reset the mana regeneration rate until levelling up once again, which returns the regeneration rate to its normal level.

### Steps to Reproduce

1. Level up
2. Die

### Version

1.18.2-1.2.4

### Forge Version

40.2.0

**Comment by IchHabeHunger54** [comment]
Fix will ship with the next update.
