### ISSUE TITLE
[Bug]: Game crash upon opening spell recipe

### ISSUE THREAD

**Issue by BlackfeatherMain** [MinecraftschurliMods/Ars-Magica-Legacy#388]
### Describe the bug

Upon attempting to open the spell recipe, the game crashes immediately. Tested with Self + Heal and Projectile + Lightning, newest version of AM2 Legacy for 1.
Additionally, the crafting altar will not accept a Blank Rune as the starting reagent for the crafting recipe with the spell recipe in the lectern-the blank rune simply sits on the ground. I suspect the two issues are related. Tested with two different altar block types and caps (mossy stone brick + moonstone, end brick + sunstone)

### Steps to Reproduce

1. Place down an Inscription Table, and craft a spell
2. Attempt to open the spell recipe. 
3. game crash

### Expected behavior

I believe the intended behavior is for the game to not crash when I open the spellbook, and instead give me the full list of necessary ingredients. 
For the crafting altar, I believe it's supposed to make the ingredient disappear and then above the lectern with the spell recipe in it, the next 

### Version

1.18.2-1.2.4

### Forge Version

40.2.0

### Other Mods

None, other than the required dependencies. 

### Log

```shell
https://paste.ee/p/8Y0X8
```

**Comment by BlackfeatherMain** [comment]
apologies for the mild snarkiness in expected behavior-it is intended as humor and not any disrespect towards the mod creators.

**Comment by IchHabeHunger54** [comment]
I can't reproduce this, everything works as intended. Try reproducing without Apotheosis and Placebo (those were showing up in the crash report), maybe they do something unexpected? If that doesn't work, please provide a screenshot of the Inscription Table GUI when trying to craft a spell - chances are this is an issue with the Inscription Table.

**Comment by ShadoDragon** [comment]
I am also seeing this issue. I successfully crafted the spell recipe book. When I try to open the recipe book it crashes the game. I tried crafting the recipe anyway. When I threw the final scroll into the altar it crashed the game, and now I can't get back in. I am running this on a server. To test, I went into a single player game after removing all other mods. No change, opening the recipe book still crashes t he game
[crash-2023-06-04_22.45.09-client.txt](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/11648590/crash-2023-06-04_22.45.09-client.txt)

**Comment by IchHabeHunger54** [comment]
1) Try reproducing in a fresh instance without Twilight Forest and Xaero's (I doubt that they do anything, but the possibility is there).
2) Please tell me the spell combination you're using, and show a screenshot of the Inscription Table interface when making the spell recipe.

**Comment by ShadoDragon** [comment]
Trying to use projectile and dig

A couple of things. If I click the Create Spell button in the table. the game crashes. If I just put the book and quill in and pull it out it doesn't crash until I try to read the book.

[crash-2023-06-05_10.25.50-client.txt](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/11654706/crash-2023-06-05_10.25.50-client.txt)
![Untitled-1](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/10445577/aa95b0fa-f793-4b09-a4ff-828a0e8dd6f3)

**Comment by IchHabeHunger54** [comment]
You're crafting it wrong, that's why. The shape (Projectile or Self) goes into the brown squares, not the gray one. We are aware that this is unintuitive, and we will change it at some point in the future. The book explains this step-by-step in the Getting Started section, so stick to that for now.
