### ISSUE TITLE
[Bug]: ArsMagica and Budschie's Morph

### ISSUE THREAD

**Issue by al31ex** [MinecraftschurliMods/Ars-Magica-Legacy#389]
### Describe the bug

I use both Ars Magica Legacy and bMorph (https://www.curseforge.com/minecraft/mc-mods/budschies-morph-mod).
When I craft the arcane compendium, I can successfully use spell. But when I morph into another creature, I loose all my mana, and the mana don't regenerate (I have always 0 mana), and so I can't use spells any more. Leave the game don't solve the issue. The only way I find to have mana again is to give me a magic level. After that, everything work fine, unless I disconnect or go to the nether, where my mana leave again.
Morph version: 2.0.1

### Steps to Reproduce

Craft the Arcane Compendium
Morph into another creature, and go back to player again
Your mana is gone

### Expected behavior

I expected to keep my mana and can use spell

### Version

1.18.2-1.2.4

### Forge Version

Forge 40.2.0

### Other Mods

None

### Log

```shell
As this create no crash, I don't have any logs
```

**Comment by IchHabeHunger54** [comment]
Sorry for the late response, there's a lot of things going on regarding the mod and real life.

Does this occur on 1.19.2 as well? We are going to drop 1.18.2 support soon, so I'd only continue to investigate if it is a 1.19.2 issue as well, and backport it if that's easy enough.
