### ISSUE TITLE
[Bug]: Interaction between PMMO and AML causes crash

### ISSUE THREAD

**Issue by ElasticKnife** [MinecraftschurliMods/Ars-Magica-Legacy#390]
### Describe the bug

I was fiddling around in the glossary from the Project MMO mod, setting filters for something and the game crashed.  There's a chance this could be on their end too, but from the logs it looked like a small issue with Ars Magica.

### Steps to Reproduce

1. Play a world with both PMMO and Ars Magica Legacy.
2. Hit P (by default) and click open glossary in the top right corner.
3. The specific categories I filtered for were Requirement, Items, Mining, Use as Tool.
4. When clicking View Info, the game crashed.

### Expected behavior

I'm not quite sure as I have not played around much with PMMO, but I would think some sort of list telling me the level requirements for all the different available mining tools.

### Screenshots

![2023-05-11_10 09 54](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/20340284/feed362d-e8d4-4a02-9138-3f63a0dbb572)
![2023-05-11_10 10 14](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/20340284/d21b00b2-53d9-4d4a-99d9-b8defa52a609)

### Version

1.18.2-1.2.4

### Forge Version

40.2.2

### Other Mods

pmmo-1.18.2-6.4.0

### Log

[https://bytebin.lucko.me/HloygEs5ll](https://bytebin.lucko.me/HloygEs5ll)

**Comment by IchHabeHunger54** [comment]
This looks like it's related to a display bug with infinity orbs.

This is only solvable for us to a limited extent: we can, of course, make infinity orbs fallback to a default color instead of crashing; however this will not display the items correctly. The correct display of item subtypes would have to be done on their end. So you might want to report it to them too; feel free to link them here.

We will, however, take care of the crash and add the fallback.

**Comment by Caltinor** [comment]
If I understand this bug correctly, the Infinity Orb Item requires some NBT data to display properly, but that data is not present when the user experiences the crash.  

In the menu shown above where the crash occurs, the menu grabs all items from the ForgeRegistries and then uses a default instance of that object for itemstack rendering.  I would expect if all assumptions are true that any mod grabbing this item from the registry and attempting to render it would have this same crash.  

If all assumptions are true, i think a fallback is the right approach.  I am open to catches on the pmmo side if that is necessary as well.

**Comment by IchHabeHunger54** [comment]
For proper display, the PMMO side would probably need to add item stack variants support, similar to what JEI or the creative menu does for things like potions. Otherwise, only the default (unusable) version of the item would appear. Which might not be a big issue, but still notable.
