### ISSUE TITLE
Solar and Lunar

### ISSUE THREAD

**Issue by priverOk** [MinecraftschurliMods/Ars-Magica-Legacy#396]
Не имеет крафта на Git модификаций Solar и Lunar(для spels) из-за этого невозможно дальше пройти по моду и в общем делает его бесполезным.

**Comment by IchHabeHunger54** [comment]
We don't understand Russian, please use English.

**Comment by priverOk** [comment]
It does not have crafting on Git for Solar and Lunar modifications (for spels) because of this it is impossible to go further through the mod and generally makes it useless.

**Comment by IchHabeHunger54** [comment]
? There are recipes for solar and lunar. I don't understand what the problem is here.
