### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheNimbleNinja** [MinecraftschurliMods/Ars-Magica-Legacy#405]
### Describe the bug

crash on startup

### Expected behavior

not crash

### Version

1.19.2-1.3.0

### Forge Version

43.2.21

### Other Mods

a modpack
[Project equivlance new horizons 3-alpha 1.zip](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/12208312/Project.equivlance.new.horizons.3-alpha.1.zip)

there wasnt a debug log so couldnt give you that

**Comment by Minecraftschurli** [comment]
We can not help you just based on "crash on startup" we need some kind of crashlog

**Comment by IchHabeHunger54** [comment]
If you don't have a debug.log, it's likely because you're using CurseForge and that turns off the debug.log for some reason. Turn it on again in the settings, then reproduce the crash and send the debug.log to us.

**Comment by IchHabeHunger54** [comment]
Version 1.3.0 was updated on CurseForge. Please get the new jar instead, that should hopefully fix your problem.
