### ISSUE TITLE
[Bug]: problems with early progression

### ISSUE THREAD

**Issue by JCsvg** [MinecraftschurliMods/Ars-Magica-Legacy#414]
### Describe the bug

every time I create a world in survival without codes, I can't access the oculus or any game items even having done the basic book, when I create in creative I can access them but when I create in survival world I can't.

### Steps to Reproduce

create a world in survival without cheats;
make the base book;
try accessing the oculus;

### Expected behavior

a message will appear saying that a mystical force is preventing you from using this

### Screenshots

![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/127432464/a44d2b21-123e-49ba-8263-2f40da925be4)

### Version

1.18.2-1.2.0

### Forge Version

3.2.4

**Comment by IchHabeHunger54** [comment]
Please update, that bug should be fixed in newer versions.
