### ISSUE TITLE
[Bug]: Can't see any of the Spell Ingredients in the Crafting Altar with Rubidium/Embeddium installed

### ISSUE THREAD

**Issue by Ereshkigal101** [MinecraftschurliMods/Ars-Magica-Legacy#424]
### Describe the bug

Title sums it up pretty much, can't see anything after I put down my Spell Ingredients book into the Lectern.

### Steps to Reproduce

1. Made the altar using Polished Deepslate, Catalysts are Iron Blocks.
2. Put in the Spell Book Ingredients list into the Lectern
3. Nothing shows up.

### Expected behavior

I expected stuff to show up, like the rune on the top of the structure or the items being shown above the lectern.

### Screenshots

![2023-10-22_23 56 28](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/66820531/b5552dae-7e05-4fb4-a69c-6266e02d8883)

### Version

1.18.2-1.3.0

### Forge Version

40.2.4

### Other Mods

![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/66820531/61b6a493-5cd9-41f0-a459-da265c80b7ba)
![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/66820531/fe539bad-4f8a-47d2-bcce-396762d28e77)
![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/66820531/7af697c8-96f6-4e9d-b732-a20a502a355a)
![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/66820531/41d3826f-ca4f-45e7-b098-730385125b30)
![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/66820531/3e2fc6d7-caaf-4530-8ba0-eb6dc15f4e12)

**Comment by IchHabeHunger54** [comment]
Try removing Rubidium. We're planning to add Rubidium support in the future, but for now, we unfortunately don't have that.

**Comment by Ereshkigal101** [comment]
Do you know if Embeddium works instead of Rubidium so I can use shaders?

**Comment by IchHabeHunger54** [comment]
I don't know, you can try.

**Comment by Ereshkigal101** [comment]
Gave it a try, it doesn't work either sadly :( . Thank you for the help, though!

**Comment by IchHabeHunger54** [comment]
That's a bummer. Just to make sure, does it work without using either?

**Comment by Ereshkigal101** [comment]
Yeah the ingredients show up w/o using either one.
