### ISSUE TITLE
[Bug]: No way to generate Light or Dark Etherium 

### ISSUE THREAD

**Issue by darubyprincxx** [MinecraftschurliMods/Ars-Magica-Legacy#445]
### Describe the bug

In the Compendium, it's said that Etherium generators during spell crafting all burn Vinteum dust to actually generate the required source. This works with a normal Obelisk, which has a UI, but when I tried to do the same with a Celestial Prism it both didn't let me right click it to connect it to the Crafting Altar and didn't have a UI letting me burn Vinteum in it. I also noticed that the Black Aurem generator didn't have a UI either. Not sure if this is a legitimate bug or just not implemented yet. 

### Steps to Reproduce

1. Following the steps in the Arcane Compendium, build a Crafting Altar. 
2. Place down a Celestial Prism nearby (requires Creative Mode, since the ritual to summon the Prism also doesn't work) 
3. Attempt to link Prism and Altar using Topaz Wrench

### Expected behavior

A UI to pop up, allowing me to input Vinteum Dust into the Prism like it does for the Obelisk. 

### Screenshots

![image](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/154827551/85410f2e-bed2-4295-a31c-19d67b75e874)

### Version

1.18.2-1.3.0

### Forge Version

40.2.0

### Other Mods

The instance that the server is on has a lot of them (will list if requested), but I also tested this with the mod alone installed and it didn't work there either.

### Log

```shell
Checked the logs and no errors appeared. It didn't even register that I was trying to do anything. Will provide if requested, however.
```

**Comment by Minecraftschurli** [comment]
1. in 1.18.2 light and dark etherium are not implemented
2. 1.18.2 is no longer maintained as we have enough on our plates with newer versions

**Comment by darubyprincxx** [comment]
that makes sense, thank you and good luck with the newer versions o7
