### ISSUE TITLE
[Bug]:  Too low mana to cast any spells.. starting from mana level one. 

### ISSUE THREAD

**Issue by OverseerSutekh** [MinecraftschurliMods/Ars-Magica-Legacy#448]
### Describe the bug

I started playing with the Ars Magica Legacy mod with a few other mods. Everything works so far, everything seemed okay.  Crafting the spells? Works fine. But when I started trying to cast the spells I made, I can't cast anything. It says "not enough mana!" This is after I had crafted the Arcane Compendium and had gotten to mana level one. Supposedly. I can see my mana bar, but it was originally at half mana, and when I closed down the game, and re-opened it, my mana bar is now empty(?), it has no blue bar inside of it., as seen in picture 1A.
![Minecraft_Picture_1A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/cc404b08-4cb0-410c-af5a-c891536d6c44)
The spell I am trying to use is the simple Touch-Dig spell. 

### Steps to Reproduce

I don't know how I did it? Maybe it's in conflict with another mod?

### Expected behavior

The spell activates, digs the block and consumes mana in doing so. 

### Screenshots

![Minecraft_Picture_1A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/d7d2a4c6-07e7-4942-86a8-973011c11e39)

### Version

1.18.1-0.0.1

### Forge/NeoForge Version

20.4.232

### Other Mods

Mods Used:

Advanced Shields - NeoForge!
morevanillashields-1.0.2-1.20.4-neoforge.jar

Ars Magica: Legacy
arsmagicalegacy-1.20.4-1.4.0.jar

Bagus Lib
bagus_lib-1.20.4-8.8.2.jar

Breedable Killer Rabbit
breedablekillerrabbit-1.20.4-3.5.jar

Collective
collective-1.20.4-7.54.jar

Configured
configured-neoforge-1.20.4-2.2.3.jar

Corpse
corpse-neoforge-1.20.4-1.0.12.jar

Dragon Mounts Remastered
Dragon Mounts Remastered-1.20.4-1.0.1.jar

Earth Mobs
earthmobsmod-1.20.4-16.3.1.jar

Friends&Foes - Beekeeper Hut (Forge/NeoForge)
friendsandfoes-beekeeperhut-neoforge-mc1.20.4-2.0.0.jar

Friends&Foes - Flowery Mooblooms (Forge/NeoForge)
friendsandfoes-flowerymooblooms-neoforge-mc1.20.4-2.0.1.jar

Friends&Foes (Forge/NeoForge) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Rascal, Tuff Golem)
friendsandfoes-neoforge-mc1.20.4-2.0.10.jar

Gaggle of Golems
Gaggle of Golems-1.4.0 (NeoForge 1.20.1).jar

GeckoLib
geckolib-neoforge-1.20.4-4.4.4.jar

Handcrafted
handcrafted-neoforge-1.20.4-3.2.1.jar

Just Enough Items (JEI)
jei-1.20.4-neoforge-17.3.0.49.jar

Paladin's Furniture
paladin-furniture-mod-1.2.1-neoforge-mc1.20.4.jar

Patchouli
Patchouli-1.20.4-85-NEOFORGE.jar

Resourceful Lib
resourcefullib-neoforge-1.20.4-2.4.10.jar

The Aether
aether-1.20.4-1.4.1-neoforge.jar

The Twilight Forest
twilightforest-1.20.4-4.4.2235-universal.jar

Xaero's Minimap
Xaeros_Minimap_24.1.1_NeoForge_1.20.4.jar

Xaero's World Map
XaerosWorldMap_1.38.4_NeoForge_1.20.4.jar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OverseerSutekh** [comment]
I will also add some more pictures of the spell I am using (or trying to use) as well as it's components and such stuff.
![Minecraft_Picture_4A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/0a9fbbf7-c9ff-4427-bbe5-f457287fe5d9)
![Minecraft_Picture_5A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/cab2b3f5-46e1-4840-bf58-af61bcf8854a)
![Minecraft_Picture_6A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/4239d078-546e-4cba-8d16-501045b9d421)
![Minecraft_Picture_7A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/eb676cc8-828e-4e2e-add1-6cb6e6aaa853)
![Minecraft_Picture_2A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/8f558458-5ebc-4865-bccd-453f095c3e3c)
![Minecraft_Picture_3A](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/assets/168507893/af7228e1-0dfa-47e0-8130-b2615bc8ecf4)

**Comment by IchHabeHunger54** [comment]
Known issue with leveling not correctly activating, will be fixed soon.

**Comment by OverseerSutekh** [comment]
Thank you!

**Comment by OverseerSutekh** [comment]
I have another question if that is alright. Would I have to create a whole new world when this issue is resolved, or could I keep my old world? Sorry for bothering ya. Hope you have a nice restful day!

**Comment by IchHabeHunger54** [comment]
The issue should be fixed in the latest version.

Also, you can generally keep your existing world, however you might have to reset your leveling (using `/arsmagicalegacy magic_xp set @p 0 levels`) and craft the compendium again.

**Comment by OverseerSutekh** [comment]
Oh! Thank you so very much! :D  
And thank you for the command! I'll go test it now!

**Comment by OverseerSutekh** [comment]
JUST TESTED IT AND IT WORKS!! WOOOO HOOOO!! XD 
Thank you again IchHabeHunger54!! You are the BEST!! I've always wanted to try this mod ever since I first saw it way back in the early 2010's and now I CANNN!! 
Again, thank you very, very much.  I hope you have a lovely day/week/year(s).
