### ISSUE TITLE
[Bug]: AOE Crashes server

### ISSUE THREAD

**Issue by SharkOSix** [MinecraftschurliMods/Ars-Magica-Legacy#449]
### Describe the bug

Making an Dig AOE spell and it crashes when I throw TNT. 

I don't know if its something in the modpack causing issue 
(Modpack: Sanguine Fantasy)

### Steps to Reproduce

1. Join a multiplayer server
2. Make a book with Dig > AOE
3. Put it in alter
4. Get to the TNT drop 
5. Put the TNT in
6. Crash the server 

### Expected behavior

Immediate server shutdown

### Version

1.20.1-1.4.0

### Forge/NeoForge Version

47.2.0 

### Other Mods

Right Click, Get Crops
right_click_get_crops-1.20.1-1.6.0.12.jar
TeamCoFH
SmartBrainLib (Forge/Fabric/Quilt)
SmartBrainLib-forge-1.20.1-1.14.jar
Scimiguy
Structurize
structurize-1.20.1-1.0.718-BETA.jar
Raycoms
Tax' Village Architect
TaxVillageArchitect+M.1.20.1+ForM.1.1.1.jar
Taknax
TerraBlender (Forge)
TerraBlender-forge-1.20.1-3.0.1.4.jar
TheAdubbz
TownTalk
towntalk-1.20.1-1.0.1.jar
Raycoms
U Team Core
u_team_core-forge-1.20.1-5.1.4.289.jar
HyCraftHD
Vanilla Expanded - Orcz
Orcz_0.87_1.20.1.jar
duke2die4
Villager Death Messages
villagerdeathmessages-1.20.1-3.3.jar
Serilum
Villager Names
villagernames-1.20.1-7.3.jar
Serilum
Waystones
waystones-forge-1.20-14.1.3.jar
BlayTheNinth
Waystones Teleport Pets
WaystonesTeleportPets-1.20-1.20.1--1.2.jar

### Log

```shell
Ars Magica    /mods/arsmagicalegacy-1.20.1-1.4.0.jar    05th May 2024 22:53 PM    Found in crash report thread dump
is all its giving me unfortunately <--- From Owner
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Minecraftschurli** [comment]
1. Dig AOE in that order can't even work
2. that "log" is by far not enough for us to find out what's happening
