### ISSUE TITLE
[Bug]: Altar core crashing

### ISSUE THREAD

**Issue by Giga734** [MinecraftschurliMods/Ars-Magica-Legacy#455]
### Describe the bug

i have built the altar but when i placed the altar core and the lever the altar core merged with the other altar blocks, and then when i tried to send the dark etherium to the altar core when i right clicked the core the game crashes everytime, i notticed that when i place the lever to full build the altar, the altar core merge with the blocks, and when i break the lever, the altar core go back to normal

### Steps to Reproduce

1. Build the altar
2. Build the Dark etherium obelisk (and then do the black aurem)
3. fill the black aurem and do the summon spell
4. try to send the dark etherium to the altar core (i`m crashing in this step because the altar core is merged with the altar blocks)

### Expected behavior

i dont know why the altar core is merging with the other altar blocks, but its not normal, i was expecting that the mod works normally

### Screenshots

arsmagicalegacy-1.20.1-1.4.0

### Version

1.20.1-1.4.0

### Forge/NeoForge Version

47.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IchHabeHunger54** [comment]
I somehow missed this issue, my apologies. If the issue still persists on the latest version, please provide a log on [Gist](https://gist.github.com/), otherwise we cannot provide further support.
