### ISSUE TITLE
[Bug]: Can't Unlock Silver Spells

### ISSUE THREAD

**Issue by paanpu** [MinecraftschurliMods/Ars-Magica-Legacy#457]
### Describe the bug

After I Craft the unlock spells. I Just Don't Unlock The Spells Like Fire Storm, Starstrike or the Time Spells

### Version

1.20.1-1.4.0

### Forge/NeoForge Version

47.3.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Minecraftschurli** [comment]
what spells did you craft and did you cast them?
Note that we changed the required spells from the original mod slightly

**Comment by paanpu** [comment]
I Tried To Craft Starstrike and Fire Rain

Am Fr., 19. Juli 2024 um 07:33 Uhr schrieb Minecraftschurli <
***@***.***>:

**Comment by Minecraftschurli** [comment]
what spell parts, if you are following a wiki it probably is wrong

**Comment by paanpu** [comment]
ok Thanks

Am Fr., 19. Juli 2024 um 22:18 Uhr schrieb Minecraftschurli <
***@***.***>:
