### ISSUE TITLE
[Bug]: Mana bar and Exaust bar doesn't appear starting from level one

### ISSUE THREAD

**Issue by Nagmy** [MinecraftschurliMods/Ars-Magica-Legacy#458]
### Describe the bug

I started to play ars magica some days ago on Minecraft 1.20.4, and since then I couldn't use any spell on survival mode only on creative mode.
It can happen 2 problems, sometimes only appear 1 bar on bottom right side of screen, or it can appear all 3 bars the level,mana, and exhaust bar correctly, but mana won't regenerate.

### Steps to Reproduce

Create Arcane Compendium, appears only level bar on bottom right side of screen
If you use /arsmagicalegacy magic_xp add  @a 5
Everything will appear normally on the bottom right side of the screen
Its the same procedure to make the mana bar regenerate when appears all 3 bars.

### Expected behavior

When you create Arcane Compedium it's supposed to appear 3 bars in this sequence, 1º level bar, 2º mana bar, 3º exhaust bar sometimes this doesn't happen, or if happens, the mana bar won't regenerate.

### Screenshots

With the problem
![image](https://github.com/user-attachments/assets/300971cd-e012-4bc0-be11-fc99c0c0eed7)
Without the problem
![Imagem do WhatsApp de 2024-07-29 à(s) 00 49 44_c279b06c](https://github.com/user-attachments/assets/a8f32261-e0a3-4ae2-be57-cc72a2be94a6)

### Version

1.20.1-1.4.0

### Forge/NeoForge Version

20.4.237

### Other Mods

Geckolib 1.20.4-4.4.4
Patchouli 1.20.4-85 NEOFORGE
Just Enought Items (JEI)  jei-1.20.4-neoforge-17.3.1.3
Xaero's Minimap Xaeros_Minimap_24.2.0_NeoForge_1.20.4
Traveler's Backpack travelersbackpack-neoforge-1.20.4-9.4.4
![image](https://github.com/user-attachments/assets/154e4a8f-af58-4641-83a1-9f4b36995e42)
![image](https://github.com/user-attachments/assets/9c5a3ab9-8d70-41ed-9895-c327c3693b1c)
![image](https://github.com/user-attachments/assets/de3e5c53-20cf-4a48-acaf-8cd18bd4b0c8)
![image](https://github.com/user-attachments/assets/ac7da644-2321-48fe-9515-76321d0f3b20)
![image](https://github.com/user-attachments/assets/ef7c5b0b-e533-47eb-b3e8-2bdf5a36f420)
![image](https://github.com/user-attachments/assets/01038cc6-a0e6-4a88-a38d-a78ad2485933)
![image](https://github.com/user-attachments/assets/57e7e810-322c-46a6-89a7-3665c8daead2)
![image](https://github.com/user-attachments/assets/013d6e22-0e20-436a-9c6a-01d5d5468db6)
![image](https://github.com/user-attachments/assets/89873ff6-7412-434e-a5a8-4c185f2d4b78)
![image](https://github.com/user-attachments/assets/5d67222b-9e4c-431c-af80-562f38980cf9)
![image](https://github.com/user-attachments/assets/a83f60cb-700f-41ef-985a-e0539f4fe3dc)
![image](https://github.com/user-attachments/assets/36c5fd15-7dde-4fae-a968-3405be89d468)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IchHabeHunger54** [comment]
Known issue. That being said, we don't support TLauncher or any other form of piracy.

**Comment by IchHabeHunger54** [comment]
Fixed as of 1.5.0.
